"""initial_schema

Revision ID: 9d6daee1380e
Revises:
Create Date: 2026-07-22 08:37:41.781383

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "9d6daee1380e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
