"""add generated slug column to projects

Revision ID: 0002
Revises: b316f0a5cd25
Create Date: 2026-08-08 06:40:27.813714

NOTE: this migration creates the public.slugify(text) function (used by the
generated column) and adds a UNIQUE index on it. unaccent is STABLE so it
cannot be used directly in a generated expression; slugify wraps it as
IMMUTABLE. If existing projects slugify to the same value (e.g. "Foo Bar" vs
"foo_bar", both "foo-bar"), the upgrade aborts. Check for collisions before
deploying: SELECT name, public.slugify(name) AS slug FROM projects GROUP BY
slug HAVING count(*) > 1;  (requires the unaccent contrib extension)

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | None = "b316f0a5cd25"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")
    op.execute(
        """
        CREATE FUNCTION public.slugify(value text) RETURNS text
        LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
        AS $slug$
            SELECT lower(regexp_replace(
                regexp_replace(unaccent(trim(value)), '[^[:alnum:]]+', '-', 'g'),
                '^-+|-+$', '', 'g'))
        $slug$
        """
    )
    op.add_column(
        "projects",
        sa.Column(
            "slug",
            sa.String(length=255),
            sa.Computed("public.slugify(name)"),
            nullable=False,
        ),
    )
    op.create_index(op.f("ix_projects_slug"), "projects", ["slug"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:  # pragma: no cover - rollback path, never exercised by tests
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_projects_slug"), table_name="projects")
    op.drop_column("projects", "slug")
    op.execute("DROP FUNCTION IF EXISTS public.slugify(text)")
    # ### end Alembic commands ###
