"""add generated slug column to projects

Revision ID: 0002
Revises: b316f0a5cd25
Create Date: 2026-08-08 06:40:27.813714

NOTE: this migration adds a UNIQUE index on the generated slug column. If
existing projects slugify to the same value (e.g. "Foo Bar" vs "foo_bar",
both "foo-bar"), the upgrade aborts. Check for collisions before deploying:
SELECT name, SLUG_EXPR AS slug FROM projects GROUP BY slug HAVING count(*)
> 1;  (substitute the slug expression from models.columns.SLUG_EXPR)

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from models.columns import SLUG_EXPR

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | None = "b316f0a5cd25"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "slug",
            sa.String(length=255),
            sa.Computed(SLUG_EXPR),
            nullable=False,
        ),
    )
    op.create_index(op.f("ix_projects_slug"), "projects", ["slug"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_projects_slug"), table_name="projects")
    op.drop_column("projects", "slug")
    # ### end Alembic commands ###
