"""add services table and sboms.service_id

Revision ID: 003
Revises: 002
Create Date: 2026-07-21 13:15:13.134610

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "003"
down_revision: str | None = "002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "services",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "name"),
    )
    op.create_index(op.f("ix_services_project_id"), "services", ["project_id"], unique=False)
    op.alter_column(
        "alert_configs", "severity_threshold", existing_type=sa.VARCHAR(length=20), nullable=False
    )
    op.alter_column(
        "alert_configs", "notification_type", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    op.alter_column("alert_configs", "enabled", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "alert_configs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "alert_configs",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("dependencies", "is_direct", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "dependencies",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "dependencies",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("notifications", "status", existing_type=sa.VARCHAR(length=50), nullable=False)
    op.alter_column(
        "notifications",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "notifications",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "projects",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "projects",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("pull_requests", "status", existing_type=sa.VARCHAR(length=50), nullable=False)
    op.alter_column(
        "pull_requests",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "pull_requests",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "sbom_vulnerabilities", "status", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    op.add_column("sboms", sa.Column("service_id", sa.Uuid(), nullable=True))
    op.alter_column(
        "sboms",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "sboms",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(op.f("ix_sboms_service_id"), "sboms", ["service_id"], unique=False)
    op.create_foreign_key("sboms_service_id_fkey", "sboms", "services", ["service_id"], ["id"])
    op.alter_column(
        "vulnerabilities",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "vulnerabilities",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "vulnerability_snapshots", "critical_count", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "vulnerability_snapshots", "high_count", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "vulnerability_snapshots", "medium_count", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "vulnerability_snapshots", "low_count", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "vulnerability_snapshots", "total_dependencies", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_constraint(
        op.f("vulnerability_snapshots_project_id_snapshot_date_key"),
        "vulnerability_snapshots",
        type_="unique",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("vulnerability_snapshots_project_id_snapshot_date_key"),
        "vulnerability_snapshots",
        ["project_id", "snapshot_date"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "vulnerability_snapshots", "total_dependencies", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "vulnerability_snapshots", "low_count", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "vulnerability_snapshots", "medium_count", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "vulnerability_snapshots", "high_count", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "vulnerability_snapshots", "critical_count", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "vulnerabilities",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "vulnerabilities",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint("sboms_service_id_fkey", "sboms", type_="foreignkey")
    op.drop_index(op.f("ix_sboms_service_id"), table_name="sboms")
    op.alter_column(
        "sboms",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "sboms",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("sboms", "service_id")
    op.alter_column(
        "sbom_vulnerabilities", "status", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.alter_column(
        "pull_requests",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "pull_requests",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("pull_requests", "status", existing_type=sa.VARCHAR(length=50), nullable=True)
    op.alter_column(
        "projects",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "projects",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "notifications",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "notifications",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("notifications", "status", existing_type=sa.VARCHAR(length=50), nullable=True)
    op.alter_column(
        "dependencies",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "dependencies",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("dependencies", "is_direct", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "alert_configs",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "alert_configs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("alert_configs", "enabled", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "alert_configs", "notification_type", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.alter_column(
        "alert_configs", "severity_threshold", existing_type=sa.VARCHAR(length=20), nullable=True
    )
    op.drop_index(op.f("ix_services_project_id"), table_name="services")
    op.drop_table("services")
    # ### end Alembic commands ###
