"""restore unique constraint on vulnerability_snapshots

Revision ID: 004
Revises: 003
Create Date: 2026-07-21 14:38:23.472638

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "004"
down_revision: str | None = "003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "vulnerability_snapshots", ["project_id", "snapshot_date"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "vulnerability_snapshots", type_="unique")
    # ### end Alembic commands ###
