"""add fixed_count to vulnerability_snapshots

Revision ID: 005
Revises: 004
Create Date: 2026-07-21 15:48:27.937963

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "005"
down_revision: str | None = "004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vulnerability_snapshots",
        sa.Column("fixed_count", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vulnerability_snapshots", "fixed_count")
    # ### end Alembic commands ###
