"""add fixed_at to sbom_vulnerabilities

Revision ID: 007
Revises: 006
Create Date: 2026-07-21 16:55:07.185815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '007'
down_revision: Union[str, None] = '006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sbom_vulnerabilities', sa.Column('fixed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sbom_vulnerabilities', 'fixed_at')
    # ### end Alembic commands ###
