include:
  - docker-compose/postgresql.yml
  - docker-compose/rabbitmq.yml
  - docker-compose/app.yml
  - docker-compose/caddy.yml
  - docker-compose/otel.yml
  - docker-compose/jaeger.yml

services:
  app:
    image: ghcr.io/trottomv/argus-sbomguard:${APP_VERSION:-0.0.6-beta}
    deploy:
      resources:
        limits:
          memory: ${APP_MEM_LIMIT:-512M}
          cpus: ${APP_CPU_LIMIT:-1.0}
    env_file:
      - .env
    restart: unless-stopped

  worker:
    image: ghcr.io/trottomv/argus-sbomguard:${APP_VERSION:-0.0.6-beta}
    deploy:
      resources:
        limits:
          memory: ${WORKER_MEM_LIMIT:-512M}
          cpus: ${WORKER_CPU_LIMIT:-1.0}
    env_file:
      - .env
    restart: unless-stopped

  scheduler:
    image: ghcr.io/trottomv/argus-sbomguard:${APP_VERSION:-0.0.6-beta}
    deploy:
      resources:
        limits:
          memory: ${SCHEDULER_MEM_LIMIT:-128M}
          cpus: ${SCHEDULER_CPU_LIMIT:-0.5}
    env_file:
      - .env
    restart: unless-stopped
