include:
  - docker-compose/postgresql.yml
  - docker-compose/rabbitmq.yml
  - docker-compose/mailpit.yml
  - docker-compose/app.yml
  - docker-compose/caddy.yml

services:
  app:
    build:
      context: ../app
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:-development}
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mailpit:
        condition: service_started
    ports:
      - 8000:8000
      - 50051:50051
    user: "0:0"
    volumes:
      - ./app:/app

  worker:
    build:
      context: ../app
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:-development}
    env_file:
      - .env
    user: "0:0"
    volumes:
      - ./app:/app

  scheduler:
    build:
      context: ../app
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:-development}
    env_file:
      - .env
    user: "0:0"
    volumes:
      - ./app:/app

  mailpit:
    ports:
      - 1025:1025
      - 8025:8025
